#!/usr/bin/env bash
# Regenerates docs/bug-log.md from `Bug:` trailers in commit messages (S1-14).
#
# The bug log is the highest-signal artifact in the finished repository (G-6) and was the
# weakest link in the plan, because every mitigation was a form of "be disciplined". Making it
# a byproduct of a commit message you were writing anyway is the only structural fix available.
#
# HONEST LIMIT: the CI check that runs this detects a *stale* log — the failure that actually
# happens. It cannot detect a *missing trailer* on a commit that deserved one. Nothing can.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
OUT=docs/bug-log.md

{
  cat <<'HEADER'
# Bug Log

> **Generated file — do not edit by hand.** Regenerated by `scripts/gen-bug-log.sh` from
> `Bug:` trailers in commit messages. CI fails if this file drifts from `git log`.
>
> See `docs/coding-standards.md` for the trailer format and what qualifies.

HEADER

  count=0
  while IFS= read -r sha; do
    bug=$(git show -s --format=%B "$sha" | sed -n 's/^Bug:[[:space:]]*//p' | head -1)
    [ -z "$bug" ] && continue
    count=$((count + 1))
    found=$(git show -s --format=%B "$sha" | sed -n 's/^Found-by:[[:space:]]*//p' | head -1)
    cause=$(git show -s --format=%B "$sha" | sed -n '/^Cause:/,/^\(Fix\|Bug\|Found-by\):/p' \
            | sed 's/^Cause:[[:space:]]*//' | sed '/^Fix:/d' | sed 's/^[[:space:]]*//' \
            | grep -v '^$' | tr '\n' ' ')
    fix=$(git show -s --format=%B "$sha" | sed -n '/^Fix:/,$p' \
          | sed 's/^Fix:[[:space:]]*//' | sed 's/^[[:space:]]*//' \
          | grep -v '^Co-Authored-By:' | grep -v '^$' | tr '\n' ' ')
    date=$(git show -s --format=%cs "$sha")

    printf '## %d. %s\n\n' "$count" "$bug"
    printf -- '- **Date:** %s · **Commit:** [`%s`](../../commit/%s)\n' "$date" "${sha:0:8}" "$sha"
    printf -- '- **Found by:** %s\n' "${found:-unrecorded}"
    printf -- '- **Cause:** %s\n' "${cause:-unrecorded}"
    printf -- '- **Fix:** %s\n\n' "${fix:-unrecorded}"
  done < <(git log --reverse --format=%H)

  if [ "${count:-0}" -eq 0 ]; then
    cat <<'EMPTY'
_No entries yet._

An empty log by the end of Sprint 3 is a **finding, not a success** — it means the proof
suites are not adversarial enough (G-6, delivery-plan watch list).
EMPTY
  fi
} > "$OUT"

echo "Wrote $OUT"
