"""Parse `Bug:` commit trailers into docs/bug-log.md (S1-14)."""

import re
import subprocess
import sys

HEADER = """# Bug Log

> **Generated file — do not edit by hand.** Regenerated by `scripts/gen-bug-log.sh` from
> `Bug:` trailers in commit messages. CI fails if this file drifts from `git log`.
>
> See `docs/coding-standards.md` for the trailer format and what qualifies.

"""

EMPTY = """_No entries yet._

An empty log by the end of Sprint 3 is a **finding, not a success** — it means the proof
suites are not adversarial enough (G-6, delivery-plan watch list).
"""

FIELDS = ("Bug", "Found-by", "Cause", "Fix")
FIELD_RE = re.compile(r"^(%s):\s*(.*)$" % "|".join(FIELDS))
# Any other trailer-shaped line ends the current field's continuation.
OTHER_TRAILER_RE = re.compile(r"^[A-Z][A-Za-z-]*:\s")


def parse_blocks(message):
    """Yield one dict per `Bug:` block. Continuation lines are indented or unprefixed."""
    blocks, current, field = [], None, None
    for raw in message.splitlines():
        line = raw.rstrip()
        match = FIELD_RE.match(line)
        if match:
            name, value = match.group(1), match.group(2).strip()
            if name == "Bug":
                if current:
                    blocks.append(current)
                current = {"Bug": value}
            elif current is not None:
                current[name] = value
            field = name
            continue

        if current is None or field is None:
            continue
        stripped = line.strip()
        if not stripped or OTHER_TRAILER_RE.match(line):
            field = None
            continue
        current[field] = (current.get(field, "") + " " + stripped).strip()

    if current:
        blocks.append(current)
    return blocks


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "docs/bug-log.md"
    entries = []
    raw = subprocess.run(
        ["git", "log", "--reverse", "--format=%H%x1f%cs%x1f%B%x1e"],
        capture_output=True, text=True, check=True).stdout
    for record in raw.split("\x1e"):
        if not record.strip():
            continue
        sha, date, message = record.strip("\n").split("\x1f", 2)
        for block in parse_blocks(message):
            entries.append((sha, date, block))

    parts = [HEADER]
    if not entries:
        parts.append(EMPTY)
    for index, (sha, date, block) in enumerate(entries, start=1):
        parts.append("## %d. %s\n\n" % (index, block.get("Bug", "(untitled)")))
        parts.append(
            "- **Date:** %s · **Commit:** [`%s`](../../commit/%s)\n" % (date, sha[:8], sha)
        )
        parts.append("- **Found by:** %s\n" % block.get("Found-by", "unrecorded"))
        parts.append("- **Cause:** %s\n" % block.get("Cause", "unrecorded"))
        parts.append("- **Fix:** %s\n\n" % block.get("Fix", "unrecorded"))

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("".join(parts))
    print("Wrote %s — %d entr%s" % (out_path, len(entries), "y" if len(entries) == 1 else "ies"))


main()
